version: "3.7"
services:

  application:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pgmais-application
    hostname: pgmais-application
    volumes:
      - $PWD/:/src
    ports:
      - 5000:5000